name: muslim_dialy_guide
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+7

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #####--------------------------------  Provider  ----------------------------#####
  provider: ^6.0.2
  #####----------------------------  SharedPreferences  -----------------------#####
  shared_preferences: ^2.0.13
  #####------------------------------- native pdf view  ----------------------------#####
  native_pdf_view: ^6.0.0+1
  #####-------------------------------- device info  ----------------------------#####
  device_info: ^2.0.3
  #####--------------------------------  screen  ----------------------------#####
  # screen: ^0.0.5
  #####------------------------------- Flutter toast  ----------------------------#####
  fluttertoast: ^8.0.8
  #####--------------------------------  lottie  ----------------------------#####
  lottie: ^1.2.2
  #####----------------------------  Flutter Qiblah  ----------------------------#####
  # flutter_qiblah: ^2.0.2
  #####--------------------------------  SVG  ----------------------------#####
  flutter_svg: ^1.0.3
  #####------------------------------- Google Maps  ----------------------------#####
  google_maps_flutter: ^2.1.1
  #####-----------------------------  Google Fonts  ----------------------------#####
  google_fonts: ^2.3.1
  #####--------------------------------  linkwell  ----------------------------#####
  # linkwell: ^2.0.6
  #####-----------------------------  Location  ----------------------------#####
  location: ^4.3.0
  #####-----------------------------  HTTP  ----------------------------#####
  http: ^0.13.4

  adhan: ^1.1.16
  intl: ^0.17.0
  device_info_plus: ^3.2.2
  url_launcher: ^6.0.20
  overlay_support: ^1.2.1
  # android_alarm_manager_plus: ^2.0.5
  # workmanager: ^0.4.1
  flutter_local_notifications: ^9.4.0
  flutter_native_timezone: ^2.0.0

  #####-----------------------------  Ads  ----------------------------#####
  google_mobile_ads: ^1.1.0
  
  #####-----------------------------  Firebase  ----------------------------#####
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pdf/
    - assets/json/
    - assets/arabic_quran/
    - assets/praying_time/
    - assets/elqibla/
    - assets/azkar/