name: muslim_dialy_guide
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #####--------------------------------  Provider  ----------------------------#####
  provider: ^6.0.2
  #####----------------------------  SharedPreferences  -----------------------#####
  shared_preferences: ^2.0.13
  #####------------------------------- native pdf view  ----------------------------#####
  native_pdf_view: ^6.0.0+1
  #####-------------------------------- device info  ----------------------------#####
  device_info: ^2.0.3
  #####--------------------------------  screen  ----------------------------#####
  screen: ^0.0.5
  #####------------------------------- Flutter toast  ----------------------------#####
  fluttertoast: ^8.0.8
  #####--------------------------------  lottie  ----------------------------#####
  lottie: ^1.2.2
  #####----------------------------  Flutter Qiblah  ----------------------------#####
  flutter_qiblah: ^2.0.2
  #####--------------------------------  SVG  ----------------------------#####
  flutter_svg: ^1.0.3
  #####------------------------------- Google Maps  ----------------------------#####
  google_maps_flutter: ^2.1.1
  #####-----------------------------  Google Fonts  ----------------------------#####
  google_fonts: ^2.3.1
  #####--------------------------------  linkwell  ----------------------------#####
  linkwell: ^2.0.6
  #####-----------------------------  auto_direction  ----------------------------#####
  auto_direction: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pdf/
    - assets/json/
    - assets/arabic_quran/
    - assets/praying_time/
    - assets/elqibla/
    - assets/azkar/