// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfzBiR6DAKpl1P4Uwy3FONoE_VF9J4YUA',
    appId: '1:203591081143:android:a73db8923c97abd3af8132',
    messagingSenderId: '203591081143',
    projectId: 'rebhelakhera',
    databaseURL: 'https://rebhelakhera.firebaseio.com',
    storageBucket: 'rebhelakhera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9L7y--hMIY_skhng-JDmfeyNauJBlmg',
    appId: '1:203591081143:ios:f20cac874d47f7c5af8132',
    messagingSenderId: '203591081143',
    projectId: 'rebhelakhera',
    databaseURL: 'https://rebhelakhera.firebaseio.com',
    storageBucket: 'rebhelakhera.appspot.com',
    iosClientId: '203591081143-llo8ctca5go4n3071e29nhtnvi75uf98.apps.googleusercontent.com',
    iosBundleId: 'com.maryamyehya.reb',
  );
}
